<script setup>
import { computed, ref } from 'vue'
import PageHeader from '../components/PageHeader.vue'
import StatusPill from '../components/StatusPill.vue'
import { client, formatMoney, practiceJournals, reconciliationAreas, tbRows } from '../data'

const activeTab = ref('Data intake')
const tabs = ['Data intake', 'Mappings & reconciliations', 'Financial statements']
const showAllRows = ref(false)
const journalStatus = ref(practiceJournals.map((journal) => journal.status))
const toast = ref('')
const visibleRows = computed(() => showAllRows.value ? tbRows : tbRows.slice(0, 8))
const debitTotal = computed(() => tbRows.reduce((sum, row) => sum + row.debit, 0))
const creditTotal = computed(() => tbRows.reduce((sum, row) => sum + row.credit, 0))
const closingTotal = computed(() => tbRows.reduce((sum, row) => sum + row.closing, 0))

function markJournal(index) {
  if (index !== 1) return
  journalStatus.value[index] = 'Authorized for source bridge'
  toast.value = 'AJ-002 is staged for management authorization in this prototype.'
  window.setTimeout(() => { toast.value = '' }, 3500)
}
</script>

<template>
  <div class="page">
    <PageHeader eyebrow="Accounting production" title="Accounting & TB" description="Follow the preserved raw receipt through validation, mapping, reconciliations, controlled journals and the versioned financial-statement package." action-label="Import dataset" />

    <div v-if="toast" class="toast" role="status" aria-live="polite"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4L19 6"/></svg>{{ toast }}</div>

    <section class="data-hero panel"><div class="data-file"><span class="file-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v5h5M9 13h6M9 17h6"/></svg></span><div><span class="eyebrow">Selected dataset</span><h2>TB v03 · Northstar Trading W.L.L.</h2><p>CSV receipt · parser 2.4.1 · uploaded 03 Sep 2026 · source hash <code>sha256:9c24…d1b8</code></p></div></div><div class="data-status"><StatusPill label="Validated for processing" tone="good" /><span>14 accounts · QAR · 31 Dec 2026</span><small>TB v02 fixture QAR 1.82m → AJ-001 reflected in TB v03</small></div></section>

    <section class="stats-strip compact"><div><span>Debit control total</span><strong>{{ formatMoney(debitTotal) }}</strong><small>Literal values only</small></div><div><span>Credit control total</span><strong>{{ formatMoney(creditTotal) }}</strong><small>Matches debits</small></div><div><span>Signed balance</span><strong>{{ formatMoney(closingTotal) }}</strong><small>Zero at approved precision</small></div><div><span>Mapping coverage</span><strong>100%</strong><small>14 of 14 accounts assigned</small></div></section>

    <nav class="sub-tabs" aria-label="Accounting views"><button v-for="tab in tabs" :key="tab" type="button" :class="{ active: activeTab === tab }" @click="activeTab = tab">{{ tab }}</button></nav>

    <template v-if="activeTab === 'Data intake'">
      <section class="accounting-layout"><article class="panel table-panel"><div class="panel-heading"><div><span class="eyebrow">Canonical rows</span><h2>Trial balance control table</h2></div><button type="button" class="text-button" @click="showAllRows = !showAllRows">{{ showAllRows ? 'Show fewer' : 'Show all 14 rows' }} <span aria-hidden="true">→</span></button></div><div class="table-wrap responsive-table"><table><thead><tr><th>Account</th><th>Area</th><th class="num">Debit</th><th class="num">Credit</th><th class="num">Closing</th><th>Taxonomy destination</th><th>Status</th></tr></thead><tbody><tr v-for="row in visibleRows" :key="row.code"><td><div class="account-cell"><code>{{ row.code }}</code><strong>{{ row.account }}</strong></div></td><td>{{ row.area }}</td><td class="num">{{ row.debit ? formatMoney(row.debit) : '—' }}</td><td class="num">{{ row.credit ? formatMoney(row.credit) : '—' }}</td><td class="num strong-number">{{ formatMoney(row.closing) }}</td><td>{{ row.mapped }}</td><td><StatusPill :label="row.status" :tone="row.status === 'Adjusted' ? 'warn' : 'good'" /></td></tr></tbody><tfoot><tr><th colspan="2">Control totals</th><th class="num">{{ formatMoney(debitTotal) }}</th><th class="num">{{ formatMoney(creditTotal) }}</th><th class="num">{{ formatMoney(closingTotal) }}</th><th colspan="2"><StatusPill label="Balanced" tone="good" /></th></tr></tfoot></table></div><div class="table-footnote"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 5h16v14H4zM8 9h8M8 13h8M8 17h4"/></svg><span>Source rows retain account codes as strings, including leading zeros. The rejected TB v02 remains preserved and cannot become the release base.</span></div></article><aside class="panel control-card"><div class="panel-heading"><div><span class="eyebrow">Validation run</span><h2>Checks passed</h2></div><StatusPill label="0 exceptions" tone="good" /></div><ul class="check-list"><li><span class="list-icon good">✓</span><span><strong>Entity / period / currency</strong><small>{{ client.shortName }} · 31 Dec 2026 · QAR</small></span></li><li><span class="list-icon good">✓</span><span><strong>Row uniqueness</strong><small>14 canonical keys · no duplicate dimensional rows</small></span></li><li><span class="list-icon good">✓</span><span><strong>Movement bridge</strong><small>Opening + movement agrees to closing</small></span></li><li><span class="list-icon warn">!</span><span><strong>Source replacement</strong><small>TB v03 includes AJ-001; no duplicate journal application</small></span></li></ul><button type="button" class="button secondary full-width">Download validation report</button></aside></section>
      <section class="split-grid"><article class="panel"><div class="panel-heading"><div><span class="eyebrow">Controlled journals</span><h2>Adjustments and source bridge</h2></div><button type="button" class="text-button">Open journal register <span aria-hidden="true">→</span></button></div><div class="journal-list"><div v-for="(journal, index) in practiceJournals" :key="journal.id" class="journal-row"><span class="journal-id">{{ journal.id }}</span><span><strong>{{ journal.purpose }}</strong><small>{{ journal.origin }} · {{ journal.layer }} · {{ journal.support }}</small></span><strong class="journal-amount">{{ formatMoney(journal.amount) }}</strong><StatusPill :label="journalStatus[index]" :tone="journalStatus[index].includes('Authorized') || journalStatus[index].includes('Reflected') ? 'good' : 'warn'" /><button v-if="index === 1" type="button" class="row-button" @click="markJournal(index)">{{ journalStatus[index].includes('Authorized') ? 'Staged' : 'Stage' }}</button></div></div></article><article class="panel insight-card"><span class="eyebrow">Version rule</span><h2>AJ-001 is applied once</h2><p>The replacement source TB v03 already includes the QAR 5,000 depreciation entry. The bridge records the relationship and prevents the same journal from being appended a second time.</p><div class="equation"><span>TB v02</span><b>+</b><span>AJ-001</span><b>=</b><strong>TB v03</strong></div><div class="insight-metrics"><div><span>Net PPE</span><strong>{{ formatMoney(95000) }}</strong></div><div><span>Current profit</span><strong>{{ formatMoney(175000) }}</strong></div></div></article></section>
    </template>

    <template v-else-if="activeTab === 'Mappings & reconciliations'">
      <section class="split-grid"><article class="panel"><div class="panel-heading"><div><span class="eyebrow">Dual mapping</span><h2>Statement taxonomy coverage</h2></div><StatusPill label="Reviewed" tone="good" /></div><div class="mapping-summary"><div class="mapping-ring"><strong>100%</strong><span>mapped</span></div><div><strong>Every non-zero account has a reviewed destination.</strong><p>Presentation signs remain separate from original source signs. A mapping change creates a new schedule version and impact tasks.</p></div></div><div class="mapping-bars"><div><span>Financial statement taxonomy</span><strong>14 / 14</strong><i><b style="width:100%"></b></i></div><div><span>Audit area mapping</span><strong>14 / 14</strong><i><b style="width:100%"></b></i></div><div><span>Supporting schedule links</span><strong>11 / 14</strong><i><b style="width:78%"></b></i></div></div></article><article class="panel"><div class="panel-heading"><div><span class="eyebrow">Reconciliation workspaces</span><h2>Control account status</h2></div><button type="button" class="text-button">Open workspaces <span aria-hidden="true">→</span></button></div><div class="recon-list"><div v-for="area in reconciliationAreas" :key="area.name" class="recon-row"><span class="recon-icon" :class="`tone-${area.tone}`"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 5h14v14H5zM8 9h8M8 13h5"/></svg></span><span><strong>{{ area.name }}</strong><small>{{ area.source }} · {{ area.owner }}</small></span><span class="recon-amount">{{ formatMoney(area.balance) }}</span><StatusPill :label="area.status" :tone="area.tone" /></div></div></article></section>
      <section class="panel"><div class="panel-heading"><div><span class="eyebrow">Source bridge</span><h2>What changed from TB v02 to v03</h2></div><StatusPill label="Traceable" tone="good" /></div><div class="bridge-flow"><div><span>TB v02</span><strong>{{ formatMoney(1820000) }}</strong><small>Raw source · 14-account fixture</small></div><span class="bridge-arrow" aria-hidden="true">→</span><div class="bridge-change"><span>AJ-001</span><strong>+ {{ formatMoney(5000) }}</strong><small>Debit and credit catch-up</small></div><span class="bridge-arrow" aria-hidden="true">→</span><div><span>TB v03</span><strong>{{ formatMoney(debitTotal) }}</strong><small>Validated replacement source</small></div></div></section>
    </template>

    <template v-else>
      <section class="statement-layout"><article class="panel statement-card"><div class="panel-heading"><div><span class="eyebrow">Financial Statement Package</span><h2>FS v05 · draft package</h2></div><StatusPill label="Management approved" tone="good" /></div><div class="statement-metrics"><div><span>Total assets</span><strong>{{ formatMoney(745000) }}</strong><small>Balances to liabilities + equity</small></div><div><span>Current profit</span><strong>{{ formatMoney(175000) }}</strong><small>After AJ-001</small></div><div><span>Equity</span><strong>{{ formatMoney(475000) }}</strong><small>Presentation package</small></div></div><div class="statement-bars"><div class="bar-item"><span>Assets</span><b style="height:132px"></b><strong>{{ formatMoney(745000) }}</strong></div><div class="bar-item"><span>Liabilities</span><b class="bar-blue" style="height:56px"></b><strong>{{ formatMoney(270000) }}</strong></div><div class="bar-item"><span>Equity</span><b class="bar-green" style="height:84px"></b><strong>{{ formatMoney(475000) }}</strong></div></div></article><aside class="panel"><div class="panel-heading"><div><span class="eyebrow">Package checks</span><h2>Before audit release</h2></div></div><ul class="check-list"><li><span class="list-icon good">✓</span><span><strong>Statement balance</strong><small>Assets = liabilities + equity</small></span></li><li><span class="list-icon good">✓</span><span><strong>Profit-to-equity movement</strong><small>Current-period movement reconciles</small></span></li><li><span class="list-icon warn">!</span><span><strong>Disclosure responses</strong><small>2 narrative inputs still requested</small></span></li><li><span class="list-icon warn">!</span><span><strong>Accounting technical review</strong><small>AJ-002 awaits management discussion</small></span></li></ul><button type="button" class="button primary full-width">Open statement workspace</button></aside></section>
    </template>
  </div>
</template>
