<script setup>
import { computed, ref } from 'vue'
import PageHeader from '../components/PageHeader.vue'
import StatusPill from '../components/StatusPill.vue'
import WorkflowGuide from '../components/WorkflowGuide.vue'
import Icon from '../components/Icon.vue'
import { client, formatMoney, risks, workpapers, workflowGuides } from '../data'

const activeTab = ref('Planning')
const selectedRisk = ref(risks[0])
const tabs = ['Planning', 'Fieldwork', 'Populations & samples']
const showEvidence = ref(false)
const toast = ref('')

const highRisks = computed(() => risks.filter((risk) => risk.rating === 'High').length)

function addWorkpaper() {
  toast.value = 'Working-paper draft opened. Choose the procedure, exact source snapshot, evidence links, reviewer, and conclusion owner.'
  window.setTimeout(() => { toast.value = '' }, 4000)
}
</script>

<template>
  <div class="page">
    <PageHeader eyebrow="Audit execution" title="Audit & fieldwork" description="Move from approved materiality and risk responses to populations, selected items, evidence and supported conclusions. The platform records the chain; professionals evaluate it." action-label="Add workpaper" @action="addWorkpaper" />
    <WorkflowGuide :guide="workflowGuides.audit" />
    <div v-if="toast" class="toast" role="status" aria-live="polite"><Icon name="check-circle" :size="17" />{{ toast }}</div>

    <section class="audit-hero panel"><div><span class="eyebrow">ENG-2026-0018 · {{ client.name }}</span><h2>Risk-based audit plan</h2><p>Audit plan revision 3 · approved 05 Sep 2026 · preliminary information pinned to TB v03</p></div><div class="audit-hero-meta"><StatusPill label="Plan approved" tone="good" /><span>{{ highRisks }} significant risks · 4 areas in scope</span></div></section>

    <section class="stats-strip compact"><div><span>Overall materiality</span><strong>{{ formatMoney(18000) }}</strong><small>Methodology MAT-2026-02</small></div><div><span>Performance materiality</span><strong>{{ formatMoney(12600) }}</strong><small>70% of overall · partner approved</small></div><div><span>Clearly trivial</span><strong>{{ formatMoney(900) }}</strong><small>Qualitative factors considered</small></div><div><span>Risk coverage</span><strong>86%</strong><small>6 of 7 planned responses linked</small></div></section>

    <nav class="sub-tabs" aria-label="Audit views"><button v-for="tab in tabs" :key="tab" type="button" :class="{ active: activeTab === tab }" @click="activeTab = tab">{{ tab }}</button></nav>

    <template v-if="activeTab === 'Planning'">
      <section class="audit-layout"><article class="panel risk-panel"><div class="panel-heading"><div><span class="eyebrow">Risk and assertion register</span><h2>What the plan responds to</h2></div><button type="button" class="text-button">Coverage query <Icon name="arrow-right" :size="15" /></button></div><div class="risk-table"><button v-for="risk in risks" :key="risk.id" type="button" class="risk-row" :class="{ active: selectedRisk.id === risk.id }" @click="selectedRisk = risk"><span class="risk-code">{{ risk.id }}</span><span><strong>{{ risk.area }}</strong><small>{{ risk.assertion }} · {{ risk.driver }}</small></span><span class="risk-rating" :class="`tone-${risk.tone}`">{{ risk.rating }}</span><span class="risk-status">{{ risk.status }}</span><Icon class="risk-arrow" name="arrow-right" :size="16" /></button></div></article><aside class="panel selected-risk-panel"><div class="panel-heading"><div><span class="eyebrow">Selected risk</span><h2>{{ selectedRisk.area }}</h2></div><StatusPill :label="selectedRisk.rating + ' risk'" :tone="selectedRisk.tone" /></div><dl class="detail-list"><div><dt>Assertion</dt><dd>{{ selectedRisk.assertion }}</dd></div><div><dt>Risk driver</dt><dd>{{ selectedRisk.driver }}</dd></div><div><dt>Approved response</dt><dd>{{ selectedRisk.response }}</dd></div><div><dt>Owner</dt><dd>{{ selectedRisk.owner }}</dd></div></dl><button type="button" class="button secondary full-width" @click="showEvidence = !showEvidence">{{ showEvidence ? 'Hide linked work' : 'Show linked work' }} <Icon name="arrow-right" :size="16" /></button><div v-if="showEvidence" class="linked-work"><span class="eyebrow">Linked procedures</span><p>WP-AR-01 · Population POP-AR-2026-01 · Sample plan SMP-AR-03</p></div></aside></section>
      <section class="split-grid"><article class="panel"><div class="panel-heading"><div><span class="eyebrow">Materiality rationale</span><h2>Professional selection, automated maths</h2></div><StatusPill label="Approved" tone="good" /></div><div class="rationale"><div class="rationale-number">QAR 18,000</div><p>The benchmark, selected rate, normalization and qualitative considerations are preserved with the assessment revision. The application calculates dependent thresholds but does not choose the methodology for the partner.</p></div><div class="threshold-row"><div><span>Benchmark</span><strong>Profit before tax</strong></div><div><span>Selected rate</span><strong>5.0%</strong></div><div><span>Revised</span><strong>03 Sep 2026</strong></div></div></article><article class="panel"><div class="panel-heading"><div><span class="eyebrow">Program governance</span><h2>Procedures are tailored copies</h2></div><button type="button" class="text-button">Open program <Icon name="arrow-right" :size="15" /></button></div><ul class="check-list"><li><span class="list-icon good"><Icon name="check" :size="14" /></span><span><strong>Audit program FS-AUD-2026 v2</strong><small>Approved methodology owner: Technical committee</small></span></li><li><span class="list-icon good"><Icon name="check" :size="14" /></span><span><strong>Receivables response attached</strong><small>Objective, evidence, reviewer and conclusion fields required</small></span></li><li><span class="list-icon warn"><Icon name="warning" :size="14" /></span><span><strong>AR-019 alternative work</strong><small>Open exception prevents area conclusion</small></span></li></ul></article></section>
    </template>

    <template v-else-if="activeTab === 'Fieldwork'">
      <section class="panel"><div class="panel-heading"><div><span class="eyebrow">Working papers</span><h2>Evidence-to-conclusion workspace</h2></div><span class="muted-label">{{ workpapers.length }} workpapers</span></div><div class="workpaper-grid"><article v-for="workpaper in workpapers" :key="workpaper.id" class="workpaper-card"><div class="workpaper-top"><span class="workpaper-id">{{ workpaper.id }}</span><StatusPill :label="workpaper.status" :tone="workpaper.tone" /></div><h3>{{ workpaper.title }}</h3><p>{{ workpaper.area }} · {{ workpaper.evidence }} evidence snapshots</p><div class="workpaper-stage"><span>{{ workpaper.stage }}</span><i><b :style="{ width: workpaper.status === 'Reviewed' ? '100%' : workpaper.status === 'In review' ? '68%' : workpaper.status === 'Open' ? '48%' : '18%' }"></b></i></div><div class="card-footer"><span>Reviewer · {{ workpaper.reviewer }}</span><button type="button" class="row-button">Open <Icon name="arrow-right" :size="15" /></button></div></article></div></section>
      <section class="fieldwork-chain panel"><div class="panel-heading"><div><span class="eyebrow">Selected exception</span><h2>AR-019 · contradictory evidence</h2></div><StatusPill label="Blocks area conclusion" tone="danger" /></div><div class="chain"><div><span class="chain-number">1</span><strong>Population</strong><small>POP-AR-2026-01 · QAR 300,000 reconciled</small></div><span class="chain-arrow" aria-hidden="true">→</span><div><span class="chain-number">2</span><strong>Selected item</strong><small>AR-019 · original selection preserved</small></div><span class="chain-arrow" aria-hidden="true">→</span><div><span class="chain-number">3</span><strong>Evidence conflict</strong><small>Ageing differs from subsequent receipt</small></div><span class="chain-arrow" aria-hidden="true">→</span><div><span class="chain-number">4</span><strong>Next action</strong><small>Alternative work or supported conclusion</small></div></div></section>
    </template>

    <template v-else>
      <section class="split-grid"><article class="panel"><div class="panel-heading"><div><span class="eyebrow">Population version</span><h2>Receivables population</h2></div><StatusPill label="Reconciled" tone="good" /></div><dl class="detail-list"><div><dt>Population ID</dt><dd>POP-AR-2026-01</dd></div><div><dt>Source</dt><dd>TB v03 + AR ageing snapshot</dd></div><div><dt>Rows / control total</dt><dd>218 rows · {{ formatMoney(300000) }}</dd></div><div><dt>Selection basis</dt><dd>Specific high-value + approved manual plan</dd></div><div><dt>Fingerprint</dt><dd><code>sha256:84a5…c221</code></dd></div></dl><button type="button" class="button primary full-width">Open population <Icon name="arrow-right" :size="16" /></button></article><article class="panel"><div class="panel-heading"><div><span class="eyebrow">Sample plan</span><h2>SMP-AR-03</h2></div><StatusPill label="1 exception" tone="warn" /></div><div class="sample-summary"><div><span>Selected items</span><strong>24</strong><small>4 high value · 20 spread</small></div><div><span>Tested</span><strong>23 / 24</strong><small>One item needs alternative work</small></div><div><span>Projected impact</span><strong>{{ formatMoney(12500) }}</strong><small>Not a conclusion by threshold alone</small></div></div><div class="sample-list"><div><span class="sample-state good"><Icon name="check" :size="14" /></span><span><strong>AR-001 to AR-018</strong><small>Evidence complete · no exceptions</small></span></div><div><span class="sample-state danger"><Icon name="warning" :size="14" /></span><span><strong>AR-019</strong><small>Contradictory evidence · follow-up assigned</small></span></div><div><span class="sample-state good"><Icon name="check" :size="14" /></span><span><strong>AR-020 to AR-024</strong><small>Evidence complete · no exceptions</small></span></div></div></article></section>
    </template>
  </div>
</template>
