// The pipeline is the client-friendly, high-level explanation layer. It keeps
// the PDF-derived handoffs concise while linking each handoff to the detailed
// synthetic workspace page where the same responsibility is demonstrated.
//
// The full lifecycle has two connected levels:
//
//   RELATIONSHIP LIFECYCLE — Lead → Qualify → Convert → Group → Acceptance
//   ENGAGEMENT LIFECYCLE   — Commercial → Staffing → Audit → Review → Release

export const pipelineStages = [
  // ── RELATIONSHIP LIFECYCLE ──────────────────────────────────────────────────
  {
    id: 'lead',
    number: '01',
    phase: 'Acquire',
    lifecycle: 'relationship',
    title: 'Lead registration',
    summary: 'Capture the initial prospect contact and service interest before any professional commitment.',
    actor: 'Engagement partner / compliance',
    owner: 'Business development → Partner',
    route: 'clients',
    routeLabel: 'Open Clients & pipeline',
    destinations: {
      admin: { route: 'clients', label: 'Open Clients & pipeline' },
      accountant: { route: 'clients', label: 'View leads' },
      client: { route: 'client-home', label: 'Open portal overview' },
    },
    status: 'INTAKE',
    tone: 'navy',
    humanAction: 'The relationship owner captures the prospect name, company, email, estimated value, service type, and source. No client or engagement record is created yet.',
    portalAction: 'The portal stores the lead record separately from client and engagement data. A lead is not a client until qualified and converted through a separate professional decision.',
    documents: ['Lead record', 'Initial contact log'],
    visibility: 'Internal staff only. The prospect does not have portal access at this stage.',
    nextOwner: 'Engagement partner or audit manager',
    lanes: ['portal', 'audit'],
    icon: 'users',
  },
  {
    id: 'qualify',
    number: '02',
    phase: 'Qualify',
    lifecycle: 'relationship',
    title: 'Lead qualification',
    summary: 'Answer "Should the firm pursue this opportunity?" before committing professional acceptance resources.',
    actor: 'Engagement partner / audit manager',
    owner: 'Partner / Manager',
    route: 'clients',
    routeLabel: 'Qualify lead',
    destinations: {
      admin: { route: 'clients', label: 'Open Clients & pipeline' },
      accountant: { route: 'clients', label: 'Open leads' },
      client: { route: 'client-home', label: 'Open portal overview' },
    },
    status: 'DECISION',
    tone: 'amber',
    humanAction: 'The relationship owner reviews service fit, estimated value, conflict pre-check, source, and relationship rationale. Records a qualification decision.',
    portalAction: 'The portal transitions the lead to QUALIFIED and creates a next-owner task for conversion.',
    documents: ['Lead qualification record', 'Conflict pre-check'],
    visibility: 'Internal staff only.',
    nextOwner: 'Engagement partner',
    lanes: ['portal', 'audit'],
    icon: 'check-circle',
  },
  {
    id: 'convert',
    number: '03',
    phase: 'Convert',
    lifecycle: 'relationship',
    title: 'Client conversion',
    summary: 'A qualified lead is formally converted into a Client record, draft Engagement shell, and an unaccepted Acceptance case.',
    actor: 'Engagement partner / compliance',
    owner: 'Partner → Compliance reviewer',
    route: 'clients',
    routeLabel: 'Convert lead to client',
    destinations: {
      admin: { route: 'clients', label: 'Open Clients & pipeline' },
      accountant: { route: 'clients', label: 'View client records' },
      client: { route: 'client-home', label: 'Open portal overview' },
    },
    status: 'PENDING',
    tone: 'blue',
    humanAction: 'The partner converts the qualified lead into a real client record with legal name, registration number, and an optional client group. A draft engagement shell and acceptance case are created automatically.',
    portalAction: 'The portal creates Client, Engagement shell, and Acceptance assessment atomically. The lead is marked CONVERTED and lineage is preserved. The client is not yet accepted.',
    documents: ['Client record', 'Draft engagement shell', 'Acceptance assessment (blank)', 'Lead lineage'],
    visibility: 'Internal staff only until acceptance is complete.',
    nextOwner: 'Compliance reviewer → Engagement partner',
    lanes: ['portal', 'audit'],
    icon: 'workflow',
  },
  {
    id: 'intake',
    number: '04',
    phase: 'Accept',
    lifecycle: 'relationship',
    title: 'Client acceptance',
    summary: 'The professional accept / decline decision. Evaluates independence, conflicts, capabilities, and risk.',
    actor: 'Client + engagement partner',
    owner: 'Client contact → Partner',
    route: 'clients',
    routeLabel: 'Open Clients & acceptance',
    destinations: {
      admin: { route: 'clients', label: 'Open Clients & acceptance' },
      accountant: { route: 'accountant-client', label: 'View client details' },
      client: { route: 'client-details', label: 'Open Client details' },
    },
    status: 'DECISION',
    tone: 'amber',
    humanAction: 'The client answers the business-details questionnaire. The engagement partner evaluates independence, capability, conflicts, and continuance before accepting the relationship.',
    portalAction: 'The portal stores a versioned submission, routes the acceptance checklist to the accountable partner, and keeps the decision separate from any quote or login.',
    documents: ['Client details', 'Acceptance questionnaire', 'Continuance record'],
    visibility: 'The client sees their submitted facts and follow-up questions. Internal acceptance rationale remains staff-only.',
    nextOwner: 'Engagement partner',
    lanes: ['client', 'portal', 'audit'],
    icon: 'shield',
  },
  // ── ENGAGEMENT LIFECYCLE ────────────────────────────────────────────────────
  {
    id: 'commercial',
    number: '05',
    phase: 'Commercial',
    lifecycle: 'engagement',
    title: 'Quote & engagement letter',
    summary: 'Price the work, agree terms, and record the authorized service scope.',
    actor: 'Finance + engagement partner',
    owner: 'Finance → Partner → Client',
    route: 'blueprint',
    routeLabel: 'Open V5 operating model',
    destinations: {
      admin: { route: 'blueprint', label: 'Open V5 operating model' },
      accountant: { route: 'accountant-home', label: 'Open accountant overview' },
      client: { route: 'client-home', label: 'Open portal overview' },
    },
    status: 'TERMS',
    tone: 'blue',
    humanAction: 'Finance calculates the estimated cost and fee. The partner authorizes the scope and the client reviews the quotation and engagement letter.',
    portalAction: 'The portal links the quote, fee agreement, scope, and signature state to the same engagement record. A payment or quote status cannot impersonate acceptance.',
    documents: ['Cost estimate', 'Quotation', 'Engagement letter'],
    visibility: 'The client sees the commercial documents and signature request. Internal margin and staffing notes remain private.',
    nextOwner: 'Client contact + partner',
    lanes: ['client', 'portal', 'audit', 'finance'],
    icon: 'file',
  },
  {
    id: 'staffing',
    number: '06',
    phase: 'Activate',
    lifecycle: 'engagement',
    title: 'Team assignment & commencement',
    summary: 'Assign the engagement team, verify the advance, and formally start the audit.',
    actor: 'Partner / audit manager',
    owner: 'Partner → Manager → Senior',
    route: 'engagements',
    routeLabel: 'Open Engagement workspace',
    destinations: {
      admin: { route: 'engagements', label: 'Open Engagement workspace' },
      accountant: { route: 'accountant-home', label: 'Open accountant overview' },
      client: { route: 'client-home', label: 'Open portal overview' },
    },
    status: 'GATED',
    tone: 'green',
    humanAction: 'The partner assigns the Engagement Partner, Audit Manager, Audit Senior, and at least one Preparer with planned hours and dates. Finance verifies the required advance. START AUDIT is committed.',
    portalAction: 'The portal validates the staffing profile, advance verification, and acceptance before allowing START_AUDIT. The audit commencement event is recorded with actor and timestamp.',
    documents: ['Team assignment record', 'Advance verification', 'Audit commencement event'],
    visibility: 'Internal audit team only. The client receives the audit announcement on commencement.',
    nextOwner: 'Audit senior',
    lanes: ['portal', 'audit', 'finance'],
    icon: 'key',
  },
  {
    id: 'planning',
    number: '07',
    phase: 'Plan',
    lifecycle: 'engagement',
    title: 'Plan & announce',
    summary: 'Translate the accepted scope into people, dates, procedures, and a clear start message.',
    actor: 'Audit senior + manager',
    owner: 'Audit senior → Manager',
    route: 'engagements',
    routeLabel: 'Open Engagement workspace',
    destinations: {
      admin: { route: 'engagements', label: 'Open Engagement workspace' },
      accountant: { route: 'accountant-home', label: 'Open accountant overview' },
      client: { route: 'client-home', label: 'Open portal overview' },
    },
    status: 'READY',
    tone: 'blue',
    humanAction: 'The senior drafts the audit plan with staff involvement, duration, milestones, and deadlines. The manager reviews the planned approach before the client is told fieldwork is beginning.',
    portalAction: 'The portal publishes the approved announcement, creates the request schedule, and sends notifications without exposing internal risk deliberations.',
    documents: ['Audit plan', 'Audit announcement letter', 'Milestone schedule'],
    visibility: 'The client sees the start notice and published dates. Internal staffing, risk, and review notes stay with the audit team.',
    nextOwner: 'Client contact + audit senior',
    lanes: ['client', 'portal', 'audit'],
    icon: 'calendar',
  },
  {
    id: 'evidence',
    number: '08',
    phase: 'Collect',
    lifecycle: 'engagement',
    title: 'Client uploads & PBC',
    summary: 'Request, receive, and accept evidence with a durable receipt and clear clarification loop.',
    actor: 'Client + audit senior',
    owner: 'Client contact → Senior',
    route: 'pbc',
    routeLabel: 'Open PBC portal',
    destinations: {
      admin: { route: 'pbc', label: 'Open PBC portal' },
      accountant: { route: 'pbc', label: 'Open PBC portal' },
      client: { route: 'client-home', label: 'Open portal requests' },
    },
    status: 'EVIDENCE',
    tone: 'amber',
    humanAction: 'The client uploads the trial balance, supporting documents, and prior audited financial statements against the matching request.',
    portalAction: 'The portal records the request, file version, receipt hash, due date, and notification. The senior accepts the evidence or requests clarification; an upload is not silently treated as usable.',
    documents: ['PBC request list', 'Trial balance (Excel)', 'Supporting documents', 'Prior audited FS'],
    visibility: 'The client sees assigned requests, receipt state, and clarification prompts. Internal risk scoring and review points are hidden.',
    nextOwner: 'Audit senior',
    lanes: ['client', 'portal', 'audit'],
    icon: 'inbox',
  },
  {
    id: 'draft-response',
    number: '09',
    phase: 'Execute',
    lifecycle: 'engagement',
    title: 'Audit & Draft FS',
    summary: 'Turn accepted evidence into working papers, draft statements, and a paired client response.',
    actor: 'Audit senior + manager + client',
    owner: 'Senior → Manager → Client',
    route: 'accounting',
    routeLabel: 'Open Accounting & TB',
    destinations: {
      admin: { route: 'accounting', label: 'Open Accounting & TB' },
      accountant: { route: 'accounting', label: 'Open Accounting & TB' },
      client: { route: 'client-home', label: 'Open portal overview' },
    },
    status: 'WORKING',
    tone: 'blue',
    humanAction: 'The senior performs procedures, prepares the draft financial statements, and sends a Management Information Request letter for client explanations and responses.',
    portalAction: 'The portal links the validated TB, working-paper snapshot, Draft FS, and information request to one generation. The manager receives an internal notification when the package changes.',
    documents: ['Validated TB package', 'Working papers', 'Draft financial statements', 'Management Information Request'],
    visibility: 'The client sees the Draft FS and information request published for response. Internal audit procedures and review comments remain staff-only.',
    nextOwner: 'Client finance contact → Manager',
    lanes: ['client', 'portal', 'audit'],
    icon: 'clipboard',
  },
  {
    id: 'review',
    number: '10',
    phase: 'Conclude',
    lifecycle: 'engagement',
    title: 'Senior → Manager → Partner review',
    summary: 'Three-level professional review: Senior clears workpapers, Manager completes the file, Partner forms the opinion.',
    actor: 'Senior + manager + partner',
    owner: 'Senior → Manager → Partner',
    route: 'reviews',
    routeLabel: 'Open Reviews & approvals',
    destinations: {
      admin: { route: 'reviews', label: 'Open Reviews & approvals' },
      accountant: { route: 'accountant-home', label: 'Open accountant overview' },
      client: { route: 'client-home', label: 'Open portal overview' },
    },
    status: 'AUTHORITY',
    tone: 'amber',
    humanAction: 'Senior reviews workpapers. Manager evaluates the file and recommends completion. Partner approves for opinion or returns to manager. EQR reviews if required.',
    portalAction: 'The portal enforces the sequential review chain: Senior → Manager → Partner. Each level can return the file. Manager cannot complete before Senior review is done.',
    documents: ['Senior review record', 'Manager completion', 'Partner review', 'EQR record'],
    visibility: 'Manager deliberation, EQR work, and partner rationale are controlled staff records.',
    nextOwner: 'Audit partner',
    lanes: ['client', 'portal', 'audit'],
    icon: 'check-circle',
  },
  {
    id: 'release',
    number: '11',
    phase: 'Release',
    lifecycle: 'engagement',
    title: 'Final report, invoice & archive',
    summary: 'Issue the final report, close the commercial record, and preserve the evidence package.',
    actor: 'Partner + finance + client',
    owner: 'Partner → Finance → Client',
    route: 'release',
    routeLabel: 'Open Release & archive',
    destinations: {
      admin: { route: 'release', label: 'Open Release & archive' },
      accountant: { route: 'accountant-home', label: 'Open accountant overview' },
      client: { route: 'client-home', label: 'Open portal overview' },
    },
    status: 'ISSUE',
    tone: 'green',
    humanAction: 'The partner authorizes the final audit report and financial statements. Finance calculates the final cost and invoice; the client receives the issued package and payment notice.',
    portalAction: 'The portal freezes the exact versions, checkpoints records protection, delivers the report and invoice through approved channels, and archives the manifest without overwriting prior issues.',
    documents: ['Final audit report + FS', 'Final cost summary', 'Invoice', 'Archive manifest'],
    visibility: 'The client sees the issued report, financial statements, invoice, and delivery receipt. Records and amendment controls remain governed by the firm.',
    nextOwner: 'Records custodian + client contact',
    lanes: ['client', 'portal', 'audit', 'finance'],
    icon: 'archive',
  },
]

export const pipelineLanes = [
  {
    id: 'client',
    label: 'Client',
    detail: 'Facts, files, responses and receipt of deliverables',
    icon: 'users',
    tone: 'blue',
    stages: ['intake', 'commercial', 'planning', 'evidence', 'draft-response', 'review', 'release'],
  },
  {
    id: 'portal',
    label: 'Audit portal',
    detail: 'Scopes records, versions, requests, notifications and handoffs',
    icon: 'workflow',
    tone: 'navy',
    stages: ['lead', 'qualify', 'convert', 'intake', 'commercial', 'staffing', 'planning', 'evidence', 'draft-response', 'review', 'release'],
  },
  {
    id: 'audit',
    label: 'Audit team',
    detail: 'Accepts, plans, tests, reviews and concludes',
    icon: 'clipboard',
    tone: 'amber',
    stages: ['qualify', 'convert', 'intake', 'commercial', 'staffing', 'planning', 'evidence', 'draft-response', 'review', 'release'],
  },
  {
    id: 'finance',
    label: 'Finance',
    detail: 'Cost, fee, advance, invoice and commercial close',
    icon: 'calculator',
    tone: 'green',
    stages: ['commercial', 'staffing', 'release'],
  },
]

// Lifecycle section metadata for two-level display in PipelinePage
export const pipelineLifecycles = [
  {
    id: 'relationship',
    label: 'Relationship lifecycle',
    description: 'From first prospect contact to accepted client relationship',
    icon: 'users',
    tone: 'navy',
    stages: ['lead', 'qualify', 'convert', 'intake'],
  },
  {
    id: 'engagement',
    label: 'Engagement lifecycle',
    description: 'From commercial activation through final report and archive',
    icon: 'clipboard',
    tone: 'blue',
    stages: ['commercial', 'staffing', 'planning', 'evidence', 'draft-response', 'review', 'release'],
  },
]
