// Role workspaces are the presenter-facing contract for the synthetic demo.
// They intentionally describe what each persona may do without pretending that
// the browser bundle is the production Frappe authorization plane.

export const roleWorkspaceByPersona = Object.freeze({
  'client-demo': {
    key: 'client',
    eyebrow: 'Client contributor · private portal',
    title: 'Your Northstar workspace',
    summary: 'Submit facts, respond to evidence requests, and keep the audit team informed. Internal risks, review deliberations, and unpublished opinions stay outside this view.',
    icon: 'users',
    tone: 'blue',
    scope: 'Northstar Trading W.L.L. · FY2026 · Audit + accounting',
    tasks: [
      { id: 'client-details', title: 'Confirm business details', detail: 'Submit the entity, contact, period, and requested service for review.', route: 'client-details', action: 'Open details', icon: 'users', tone: 'blue' },
      { id: 'client-pbc', title: 'Upload requested evidence', detail: 'Respond to PBC-019 and PBC-023 with the exact reporting-period files.', route: 'client-home', action: 'Open requests', icon: 'upload', tone: 'warn' },
      { id: 'client-thread', title: 'Answer information requests', detail: 'Keep questions, explanations, and next actions in one portal thread.', route: 'client-communications', action: 'Open communications', icon: 'message', tone: 'green' },
    ],
    allowed: ['Submit client details', 'Upload PBC evidence', 'Reply to a request'],
    blocked: ['View internal risk scores', 'Clear a review point', 'Approve an audit opinion'],
  },
  'client-management-demo': {
    key: 'client-management',
    eyebrow: 'Client management approver · controlled decisions',
    title: 'Approve the client-facing package',
    summary: 'Review exact commercial and financial-statement versions, record management responses, and confirm what can be published to the client portal.',
    icon: 'check-circle',
    tone: 'blue',
    scope: 'Northstar Trading W.L.L. · FY2026 · Named management approver',
    tasks: [
      { id: 'management-el', title: 'Review engagement letter', detail: 'Confirm the approved EL version, scope, responsibilities, and signature state.', route: 'client-details', action: 'Inspect terms', icon: 'file', tone: 'blue' },
      { id: 'management-fs', title: 'Respond to Draft FS', detail: 'Accept or reject the exact Draft FS version with an explanation.', route: 'accounting', action: 'Open statements', icon: 'calculator', tone: 'warn' },
      { id: 'management-delivery', title: 'View published deliverables', detail: 'Inspect only the final report and FS pair released to the named client contact.', route: 'client-home', action: 'Open portal', icon: 'folder', tone: 'green' },
    ],
    allowed: ['Accept or reject exact EL/Draft FS versions', 'Add management rationale', 'View published package'],
    blocked: ['Form audit opinion', 'Clear professional review points', 'Authorize technical release'],
  },
  'preparer-demo': {
    key: 'preparer',
    eyebrow: 'Junior / preparer · assigned work',
    title: 'Complete assigned procedures',
    summary: 'Work inside the assigned engagement, attach evidence, submit exact workpaper snapshots, and record time. Independent review remains a separate decision.',
    icon: 'clipboard',
    tone: 'blue',
    scope: 'Northstar Trading W.L.L. · FY2026 · Assigned preparer',
    tasks: [
      { id: 'preparer-pbc', title: 'Check evidence receipts', detail: 'Confirm entity, period, suitability, and the accepted snapshot before testing.', route: 'pbc', action: 'Open PBC', icon: 'inbox', tone: 'warn' },
      { id: 'preparer-workpapers', title: 'Submit workpaper snapshot', detail: 'Complete a procedure and send the immutable revision to the manager queue.', route: 'audit', action: 'Open fieldwork', icon: 'clipboard', tone: 'blue' },
      { id: 'preparer-time', title: 'Record time', detail: 'Capture hours by engagement, date, task, and role for later approval.', route: 'role-workspace', action: 'Record in workspace', icon: 'clock', tone: 'green', command: 'TIME_ENTRY' },
    ],
    allowed: ['Submit assigned workpaper', 'Attach evidence reference', 'Record time'],
    blocked: ['Self-clear significant review point', 'Approve own final work', 'Release the report'],
  },
  'audit-senior-demo': {
    key: 'audit-senior',
    eyebrow: 'Audit senior · fieldwork owner',
    title: 'Coordinate the audit file',
    summary: 'Plan the day-to-day work, create PBC requests, issue the announcement, prepare the conclusion summary, and coordinate the Draft FS handoff.',
    icon: 'workflow',
    tone: 'blue',
    scope: 'Northstar Trading W.L.L. · FY2026 · Senior assignment',
    tasks: [
      { id: 'senior-plan', title: 'Confirm plan and team', detail: 'Review milestones, staff allocation, critical items, and the G5 readiness blockers.', route: 'engagements', action: 'Open engagement', icon: 'briefcase', tone: 'blue' },
      { id: 'senior-pbc', title: 'Route PBC requests', detail: 'Create and monitor evidence requests with acceptance criteria and due dates.', route: 'pbc', action: 'Open PBC', icon: 'inbox', tone: 'warn' },
      { id: 'senior-draft', title: 'Prepare conclusion summary', detail: 'Submit the exact workpaper and Draft FS package for manager review.', route: 'audit', action: 'Open fieldwork', icon: 'file', tone: 'green' },
    ],
    allowed: ['Create PBC requests', 'Submit workpapers and conclusion summary', 'Coordinate Draft FS'],
    blocked: ['Form final opinion', 'Authorize release', 'Override a hold'],
  },
  'audit-manager-demo': {
    key: 'audit-manager',
    eyebrow: 'Audit manager · review queue',
    title: 'Review the file before partner handoff',
    summary: 'Approve planning, inspect workpaper snapshots, raise or clear appropriately segregated review points, and recommend completion.',
    icon: 'check-circle',
    tone: 'navy',
    scope: 'Northstar Trading W.L.L. · FY2026 · Manager assignment',
    tasks: [
      { id: 'manager-plan', title: 'Review planning readiness', detail: 'Check G5 owners, deadlines, announcements, and critical PBC items.', route: 'engagements', action: 'Inspect plan', icon: 'briefcase', tone: 'blue' },
      { id: 'manager-review', title: 'Clear review queue', detail: 'Review exact snapshots and respond without allowing self-review.', route: 'reviews', action: 'Open reviews', icon: 'check-circle', tone: 'warn' },
      { id: 'manager-recommend', title: 'Recommend completion', detail: 'Confirm client responses, management representations, and EQR applicability.', route: 'reviews', action: 'Open completion', icon: 'shield', tone: 'green' },
    ],
    allowed: ['Review assigned snapshots', 'Create/clear segregated review points', 'Recommend completion'],
    blocked: ['Sign partner opinion', 'Authorize final release', 'Change records policy'],
  },
  'partner-demo': {
    key: 'partner',
    eyebrow: 'Audit partner / signatory · professional authority',
    title: 'Own acceptance and final decisions',
    summary: 'Make the named professional decisions only after their evidence and review gates are satisfied. Every decision is bound to a version and rationale.',
    icon: 'shield',
    tone: 'navy',
    scope: 'Northstar Trading W.L.L. · FY2026 · Engagement partner',
    tasks: [
      { id: 'partner-accept', title: 'Resolve acceptance decision', detail: 'Review the questionnaire, evidence, clearances, and recommendation before accepting or declining.', route: 'clients', action: 'Open acceptance', icon: 'users', tone: 'warn' },
      { id: 'partner-opinion', title: 'Form audit opinion', detail: 'Inspect the exact candidate, completion recommendation, and required EQR result.', route: 'reviews', action: 'Open reviews', icon: 'check-circle', tone: 'blue' },
      { id: 'partner-release', title: 'Authorize release', detail: 'Advance the release state machine only when the matched report/FS pair and checkpoint are ready.', route: 'release', action: 'Open release', icon: 'lock', tone: 'green' },
    ],
    allowed: ['Accept/continue relationship', 'Form opinion', 'Authorize guarded release'],
    blocked: ['Rewrite records policy', 'Bypass a blocker', 'Edit another authority’s decision'],
  },
  'finance-demo': {
    key: 'finance',
    eyebrow: 'Finance team · commercial close',
    title: 'Control fees, advances, and invoice close',
    summary: 'Keep internal cost rates private, route fee approvals, verify the required advance, and reconcile invoice, time, and contribution records.',
    icon: 'calculator',
    tone: 'green',
    scope: 'Northstar Trading W.L.L. · FY2026 · Finance assignment',
    tasks: [
      { id: 'finance-estimate', title: 'Review cost estimate', detail: 'Inspect the 140-hour estimate, QAR 26,000 cost, and approved QAR 36,000 fixed fee.', route: 'blueprint', action: 'Open commercial model', icon: 'calculator', tone: 'blue' },
      { id: 'finance-advance', title: 'Verify required advance', detail: 'Confirm the QAR 9,000 advance and allocate it once to this engagement.', route: 'role-workspace', action: 'Verify advance', icon: 'check-circle', tone: 'warn', command: 'ADVANCE_VERIFY' },
      { id: 'finance-invoice', title: 'Close invoice and cost', detail: 'Reconcile 156 hours, QAR 28,700 actual cost, and QAR 27,000 remaining balance.', route: 'blueprint', action: 'Inspect close', icon: 'file', tone: 'green' },
    ],
    allowed: ['Prepare estimate', 'Verify/allocate advance', 'Create invoice and cost summary'],
    blocked: ['Change audit conclusions', 'Form opinion', 'Clear review points'],
  },
  'accountant-demo': {
    key: 'accountant',
    eyebrow: 'Accountant / preparer · accounting package',
    title: 'Prepare the scoped accounting package',
    summary: 'Validate the selected trial balance, resolve mappings and journals, prepare statement inputs, and hand the exact package to an independent reviewer.',
    icon: 'calculator',
    tone: 'green',
    scope: 'Northstar Trading W.L.L. · FY2026 · Accounting preparation',
    tasks: [
      { id: 'accountant-source', title: 'Validate TB and source', detail: 'Review control totals, source generation, reflection state, and preserved replacement history.', route: 'accounting', action: 'Open accounting', icon: 'calculator', tone: 'blue' },
      { id: 'accountant-mapping', title: 'Resolve mappings', detail: 'Unknown codes remain Unmapped and block readiness until reviewed.', route: 'accounting', action: 'Open mappings', icon: 'list-check', tone: 'warn' },
      { id: 'accountant-handoff', title: 'Submit package for review', detail: 'Send the exact package revision to the accounting reviewer or management approver.', route: 'accounting', action: 'Open handoff', icon: 'arrow-right', tone: 'green' },
    ],
    allowed: ['Import/validate TB', 'Prepare mappings and journals', 'Submit statement package'],
    blocked: ['Accept the audit relationship', 'Form opinion', 'Authorize release'],
  },
  'accounting-reviewer-demo': {
    key: 'accounting-reviewer',
    eyebrow: 'Accounting reviewer · independent package review',
    title: 'Review the accounting handoff',
    summary: 'Inspect the preparer’s source, mapping, journal, and statement revisions independently before management approval.',
    icon: 'check-circle',
    tone: 'green',
    scope: 'Northstar Trading W.L.L. · FY2026 · Accounting review',
    tasks: [
      { id: 'reviewer-source', title: 'Review source controls', detail: 'Confirm balances, selected scope, source hash, and replacement lineage.', route: 'accounting', action: 'Inspect source', icon: 'calculator', tone: 'blue' },
      { id: 'reviewer-journals', title: 'Review journal decisions', detail: 'Ensure management authorization or rejection is explicit and reasoned.', route: 'accounting', action: 'Inspect journals', icon: 'file', tone: 'warn' },
      { id: 'reviewer-submit', title: 'Submit reviewed package', detail: 'Bind the exact statement revision to its review result.', route: 'accounting', action: 'Open package', icon: 'check-circle', tone: 'green' },
    ],
    allowed: ['Review package and journals', 'Submit independent review', 'Request correction'],
    blocked: ['Approve own preparation silently', 'Form audit opinion', 'Release final package'],
  },
  'eqr-demo': {
    key: 'eqr',
    eyebrow: 'EQR reviewer · independent quality review',
    title: 'Review the exact release candidate',
    summary: 'Perform the separate EQR decision where required. The candidate, report/FS pair, and unresolved review points remain visible and version-bound.',
    icon: 'shield',
    tone: 'purple',
    scope: 'Northstar Trading W.L.L. · FY2026 · EQR assignment',
    tasks: [
      { id: 'eqr-candidate', title: 'Inspect candidate package', detail: 'Review the exact candidate revision, FS version, opinion, and completion evidence.', route: 'reviews', action: 'Open candidate', icon: 'file', tone: 'blue' },
      { id: 'eqr-decision', title: 'Record EQR decision', detail: 'Complete, return, or hold the candidate without changing audit preparation.', route: 'reviews', action: 'Open EQR', icon: 'check-circle', tone: 'warn' },
      { id: 'eqr-gate', title: 'Confirm release dependency', detail: 'A required EQR must be complete before report dating or delivery.', route: 'release', action: 'Inspect release', icon: 'lock', tone: 'green' },
    ],
    allowed: ['Inspect exact candidate', 'Record independent EQR result', 'Return a candidate for correction'],
    blocked: ['Edit workpapers', 'Sign as partner', 'Authorize delivery'],
  },
  'records-demo': {
    key: 'records',
    eyebrow: 'Records custodian · archive and preservation',
    title: 'Protect the final audit file',
    summary: 'Verify the independent checkpoint, manage action-specific legal holds, assemble the archive, and preserve linked amendment history.',
    icon: 'archive',
    tone: 'purple',
    scope: 'Northstar Trading W.L.L. · FY2026 · Records assignment',
    tasks: [
      { id: 'records-checkpoint', title: 'Verify release checkpoint', detail: 'Confirm the manifest and exact release identity before delivery is considered durable.', route: 'release', action: 'Open checkpoint', icon: 'shield', tone: 'warn' },
      { id: 'records-archive', title: 'Assemble archive', detail: 'Preserve all required outputs, event history, custody, hashes, and protection observations.', route: 'release', action: 'Open archive', icon: 'archive', tone: 'blue' },
      { id: 'records-hold', title: 'Review legal hold', detail: 'Block only the prohibited action; preservation remains allowed when appropriate.', route: 'release', action: 'Inspect holds', icon: 'lock', tone: 'green' },
    ],
    allowed: ['Verify checkpoint', 'Assemble archive', 'Record/release action-specific hold'],
    blocked: ['Form audit opinion', 'Change client acceptance', 'Edit accounting conclusions'],
  },
  'system-admin-only-demo': {
    key: 'system-admin',
    eyebrow: 'System administrator · technical controls only',
    title: 'Keep the synthetic environment healthy',
    summary: 'Manage demo actor status, session epochs, provider fault simulation, and recovery diagnostics. Technical visibility never creates professional authority.',
    icon: 'settings',
    tone: 'navy',
    scope: 'Quadrate Audit · synthetic technical administration',
    tasks: [
      { id: 'admin-actors', title: 'Manage demo actors', detail: 'Enable/disable a scoped actor and rotate their session epoch.', route: 'admin-console', action: 'Open admin console', icon: 'users', tone: 'blue' },
      { id: 'admin-provider', title: 'Inspect integration diagnostics', detail: 'Configure bounded provider faults and observe deterministic retry state.', route: 'integration', action: 'Open diagnostics', icon: 'pulse', tone: 'warn' },
      { id: 'admin-recovery', title: 'Rehearse recovery quarantine', detail: 'Capture a backup, restore into a fenced epoch, and reconcile the external checkpoint.', route: 'integration', action: 'Open recovery', icon: 'refresh', tone: 'green' },
    ],
    allowed: ['Manage synthetic users/session state', 'Configure simulation faults', 'Inspect recovery diagnostics'],
    blocked: ['Accept a client', 'Clear a professional review point', 'Form opinion or release'],
  },
  'compliance-demo': {
    key: 'compliance',
    eyebrow: 'Compliance reviewer · onboarding and records',
    title: 'Review evidence and policy boundaries',
    summary: 'Check acceptance evidence, independence/clearance conditions, and the records observations that must remain separate from professional approval.',
    icon: 'shield',
    tone: 'purple',
    scope: 'Northstar Trading W.L.L. · FY2026 · Compliance assignment',
    tasks: [
      { id: 'compliance-assessment', title: 'Review acceptance evidence', detail: 'Inspect the 62-question assessment and identify unresolved holds.', route: 'clients', action: 'Open assessment', icon: 'users', tone: 'warn' },
      { id: 'compliance-records', title: 'Inspect records protection', detail: 'Observe desired versus verified retention state without claiming enforcement.', route: 'release', action: 'Open records', icon: 'archive', tone: 'blue' },
      { id: 'compliance-architecture', title: 'Explain the boundary', detail: 'Use the architecture map to show identity, authorization, and external storage boundaries.', route: 'architecture', action: 'Open architecture', icon: 'workflow', tone: 'green' },
    ],
    allowed: ['Review evidence and clearances', 'Record records observation', 'Escalate a compliance hold'],
    blocked: ['Override a prohibition', 'Form audit opinion', 'Authorize delivery'],
  },
  'admin-demo': {
    key: 'admin',
    eyebrow: 'Presenter admin · complete synthetic control chain',
    title: 'See the whole engagement at a glance',
    summary: 'This composite presenter account can inspect every synthetic surface for demonstrations. Dedicated role accounts above preserve the real authority boundaries.',
    icon: 'grid',
    tone: 'navy',
    scope: 'Quadrate Audit · Northstar Trading W.L.L. · FY2026',
    tasks: [
      { id: 'admin-overview', title: 'Open practice control room', detail: 'Review gates, blockers, queues, and recent activity for the selected engagement.', route: 'dashboard', action: 'Open overview', icon: 'grid', tone: 'blue' },
      { id: 'admin-cycle', title: 'Run complete synthetic cycle', detail: 'Exercise the guarded positive and negative paths and inspect the evidence register.', route: 'cycle', action: 'Open cycle', icon: 'workflow', tone: 'green' },
      { id: 'admin-architecture', title: 'Explain target architecture', detail: 'Show current Vue/Vite boundaries and the future Frappe/ERPNext operating model.', route: 'architecture', action: 'Open architecture', icon: 'layers', tone: 'purple' },
    ],
    allowed: ['Inspect all synthetic surfaces', 'Run the bounded rehearsal', 'Review technical diagnostics'],
    blocked: ['Use the prototype as production authorization', 'Enable shared mode', 'Send live external messages'],
  },
})

export const roleWorkspaceFallback = roleWorkspaceByPersona['admin-demo'] || {
  key: 'role', eyebrow: 'Role workspace', title: 'Workflow workspace', summary: 'Follow the scoped work queue.', icon: 'workflow', tone: 'blue', scope: 'Synthetic engagement', tasks: [], allowed: [], blocked: [],
}

export function roleWorkspaceFor(personaId) {
  return roleWorkspaceByPersona[personaId] || roleWorkspaceFallback
}

export const roleRouteSets = Object.freeze({
  client: ['role-workspace', 'client-home', 'client-details', 'client-communications', 'artifacts', 'pipeline', 'client-architecture'],
  'client-management': ['role-workspace', 'client-home', 'client-details', 'client-communications', 'accounting', 'artifacts', 'pipeline', 'client-architecture'],
  preparer: ['role-workspace', 'pbc', 'accounting', 'audit', 'artifacts', 'pipeline', 'accountant-architecture'],
  'audit-senior': ['role-workspace', 'clients', 'engagements', 'pbc', 'audit', 'artifacts', 'pipeline', 'architecture'],
  'audit-manager': ['role-workspace', 'engagements', 'pbc', 'audit', 'reviews', 'artifacts', 'pipeline', 'architecture'],
  partner: ['role-workspace', 'clients', 'engagements', 'reviews', 'release', 'artifacts', 'pipeline', 'architecture'],
  finance: ['role-workspace', 'engagements', 'blueprint', 'release', 'artifacts', 'pipeline', 'architecture'],
  accountant: ['role-workspace', 'accountant-home', 'accountant-client', 'pbc', 'accounting', 'audit', 'artifacts', 'pipeline', 'accountant-architecture'],
  'accounting-reviewer': ['role-workspace', 'accounting', 'reviews', 'artifacts', 'pipeline', 'accountant-architecture'],
  eqr: ['role-workspace', 'reviews', 'release', 'artifacts', 'pipeline', 'architecture'],
  records: ['role-workspace', 'release', 'integration', 'artifacts', 'pipeline', 'architecture'],
  'system-admin': ['role-workspace', 'admin-console', 'integration', 'artifacts', 'architecture', 'pipeline'],
  compliance: ['role-workspace', 'clients', 'release', 'artifacts', 'architecture', 'pipeline'],
  admin: [],
})
