// Version 5 presentation data. These fixtures are intentionally separate from
// the domain scenario so the prototype can explain the complete business
// contract without pretending that a screen is a live Frappe record.

export const v5GateDefinitions = [
  { id: 'G0', title: 'Firm ready', detail: 'Approved roles, templates, methodology, safe integrations, records controls and service profile.', owner: 'Sponsor · technical · professional · security · records', status: 'READY', tone: 'good', route: 'architecture' },
  { id: 'G1', title: 'Accept / continue', detail: 'Current questionnaire, evidence, clearances and an authorized partner decision.', owner: 'Engagement partner', status: 'READY', tone: 'good', route: 'clients' },
  { id: 'G2', title: 'Commercial ready', detail: 'Staff-level estimate, fee approvals, agreed quotation and scope assumptions.', owner: 'Finance · commercial approvers', status: 'READY', tone: 'good', route: 'blueprint' },
  { id: 'G3', title: 'Terms accepted', detail: 'Exact approved Engagement Letter, correct client signatory and verified acceptance evidence.', owner: 'Engagement owner · client approver', status: 'READY', tone: 'good', route: 'blueprint' },
  { id: 'G4', title: 'Portal eligible', detail: 'Acceptance, terms, verified allocated advance, named identity and restricted binding.', owner: 'Finance · access controller', status: 'READY', tone: 'good', route: 'blueprint' },
  { id: 'G5', title: 'Fieldwork ready', detail: 'Approved plan and announcement, assigned team, critical request readiness and no blocking hold.', owner: 'Audit Senior · Manager / Partner', status: 'READY', tone: 'good', route: 'engagements' },
  { id: 'G6', title: 'Review submission ready', detail: 'Programme/workpaper submissions, complete conclusion-summary manifest and visible blockers.', owner: 'Audit Senior · next-level reviewer', status: 'NEEDS REVIEW', tone: 'warn', route: 'audit' },
  { id: 'G7', title: 'Completion ready', detail: 'Current draft response, information-request evaluation, representations, review and required EQR.', owner: 'Manager · Partner · EQR', status: 'BLOCKED', tone: 'danger', route: 'reviews' },
  { id: 'G8', title: 'Release ready', detail: 'Exact report/FS pair, opinion, final discussion, signatures, protection and current input generation.', owner: 'Authorized report signatory', status: 'BLOCKED', tone: 'danger', route: 'release' },
  { id: 'G9', title: 'Commercial close', detail: 'Final invoice, one-time advance allocation, approved time/cost snapshot and exceptions resolved.', owner: 'Finance', status: 'PENDING', tone: 'neutral', route: 'blueprint' },
  { id: 'G10', title: 'Archive / renewal', detail: 'Complete retained file, observed records controls, recovery evidence and fresh next-period decision.', owner: 'Records owner · next-period Partner', status: 'PENDING', tone: 'neutral', route: 'release', period: 'next' },
]

export const v5SystemLayers = [
  { id: 'browser', number: '01', label: 'Named user browser', kind: 'Human surface', icon: 'users', tone: 'blue', detail: 'Staff use the Desk-style workspace; clients use only the restricted portal projection.', handoff: 'Authenticated request' },
  { id: 'worker', number: '02', label: 'Cloudflare Worker boundary', kind: 'Current prototype server functions', icon: 'pulse', tone: 'green', detail: 'The existing Worker exposes fail-closed, correlation-aware demo API commands. It is an edge/server boundary, not the Frappe application host.', handoff: 'Validated command / local fallback' },
  { id: 'frappe', number: '03', label: 'Frappe + audit_practice', kind: 'V5 target application plane', icon: 'workflow', tone: 'navy', detail: 'The production target is one Frappe modular monolith that owns authorization, workflow commands, records and professional gates.', handoff: 'Guarded business intent' },
  { id: 'mariadb', number: '04', label: 'MariaDB structured records', kind: 'System of record', icon: 'database', tone: 'navy', detail: 'Clients, engagements, revisions, decisions, manifests, safety generations and durable outbox intent live here.', handoff: 'Versioned state + event' },
  { id: 'workers', number: '05', label: 'Frappe worker groups', kind: 'Bounded execution', icon: 'settings', tone: 'amber', detail: 'General, processing and restricted-record jobs run with scoped credentials, leases, attempts and reconciliation.', handoff: 'Retryable provider operation' },
  { id: 'microsoft', number: '06', label: 'Graph · SharePoint · Purview', kind: 'Document and records planes', icon: 'folder', tone: 'purple', detail: 'Selected-resource document access, exact snapshots, issued artifacts and observed protection stay in their named Microsoft planes.', handoff: 'Artifact / protection evidence' },
  { id: 'recovery', number: '07', label: 'Independent checkpoint', kind: 'Recovery plane', icon: 'archive', tone: 'green', detail: 'Release manifests and checkpoints support quarantined restore reconciliation before outward effects resume.', handoff: 'Reconciled release identity' },
]

export const v5CommercialFixture = {
  client: 'Northstar Trading W.L.L.',
  engagement: 'ENG-0018-AUD-2026',
  period: 'Year ended 31 Dec 2026',
  estimateId: 'ECS-0018-R2',
  quotationId: 'QTN-0018-2026',
  currency: 'QAR',
  feeBasis: 'Approved fixed fee',
  rows: [
    { level: 'Junior', hours: 80, costRate: 100, labourCost: 8000, sellingRate: 150, contribution: 12000 },
    { level: 'Senior', hours: 40, costRate: 200, labourCost: 8000, sellingRate: 300, contribution: 12000 },
    { level: 'Manager', hours: 12, costRate: 350, labourCost: 4200, sellingRate: 500, contribution: 6000 },
    { level: 'Partner', hours: 8, costRate: 600, labourCost: 4800, sellingRate: 800, contribution: 6400 },
  ],
  estimate: {
    budgetHours: 140,
    labourCost: 25000,
    timePrice: 36400,
    travel: 1000,
    serviceCost: 26000,
    approvedFee: 36000,
    advanceRequired: 9000,
    advanceAllocated: 9000,
    state: 'APPROVED · ADVANCE VERIFIED',
  },
  actual: {
    hours: 156,
    labourCost: 27500,
    travel: 1200,
    serviceCost: 28700,
    hoursVariance: 16,
    costVariance: 2700,
    contribution: 7300,
    contributionPercent: 20.28,
    finalInvoice: 36000,
    remainingBalance: 27000,
    invoiceState: 'DRAFT FOR FINANCE REVIEW',
  },
  controls: [
    'Internal cost rates stay out of the client quotation.',
    'A fixed fee does not create a second time-based invoice for the same scope.',
    'The QAR 9,000 advance is allocated once after the issued release milestone.',
    'Original estimate, revised budget and approved actuals remain separate snapshots.',
  ],
}

export const v5Documents = [
  { id: 'DOC-01', title: 'Client Acceptance Form', trigger: 'New client selected', owner: 'Onboarding / Senior · Partner', status: 'FINALIZED', tone: 'good', route: 'clients' },
  { id: 'DOC-02', title: 'Client Acceptance Questionnaire', trigger: '62-question assessment', owner: 'Respondents · verifiers · Partner', status: 'HOLD · UBO EVIDENCE', tone: 'warn', route: 'clients' },
  { id: 'DOC-03', title: 'Client Continuation Form', trigger: 'Existing client / current period', owner: 'Senior / Manager · Partner', status: 'READY', tone: 'good', route: 'clients' },
  { id: 'DOC-04', title: 'Client Continuation Questionnaire', trigger: 'Annual or event revalidation', owner: 'Respondents · verifiers · Partner', status: 'IN PROGRESS', tone: 'warn', route: 'clients' },
  { id: 'DOC-05', title: 'Estimated Cost of Service Sheet', trigger: 'Accepted / continued client', owner: 'Preparer · Finance', status: 'APPROVED', tone: 'good', route: 'blueprint' },
  { id: 'DOC-06', title: 'Fee Approval Record', trigger: 'Estimate / fee submitted', owner: 'Manager · Finance · Partner', status: 'APPROVED', tone: 'good', route: 'blueprint' },
  { id: 'DOC-07', title: 'Quotation', trigger: 'Approved fee', owner: 'Authorized commercial issuer', status: 'ACCEPTED', tone: 'good', route: 'blueprint' },
  { id: 'DOC-08', title: 'Audit Engagement Letter', trigger: 'Finalized quotation', owner: 'Firm reviewer · client signatory', status: 'SIGNED', tone: 'good', route: 'blueprint' },
  { id: 'DOC-09', title: 'Audit Planning Record', trigger: 'EL processing complete', owner: 'Senior / Manager · Partner', status: 'APPROVED', tone: 'good', route: 'engagements' },
  { id: 'DOC-10', title: 'Audit Announcement Letter', trigger: 'Approved plan', owner: 'Senior / Manager / sender', status: 'ISSUED', tone: 'good', route: 'engagements' },
  { id: 'DOC-11', title: 'Client Document Request / Submission Record', trigger: 'Announcement / PBC issue', owner: 'Client · Senior · Manager', status: 'IN REVIEW', tone: 'warn', route: 'pbc' },
  { id: 'DOC-12', title: 'Audit Programmes', trigger: 'Tailored programme selection', owner: 'Audit team · next-level reviewer', status: 'SUBMITTED', tone: 'warn', route: 'audit' },
  { id: 'DOC-13', title: 'Trial Balance Import', trigger: 'Current-period source receipt', owner: 'Client/source owner · reviewer', status: 'VALIDATED', tone: 'good', route: 'accounting' },
  { id: 'DOC-14', title: 'Prior-Year Audited FS', trigger: 'Applicable ongoing entity', owner: 'Client/source owner · Senior', status: 'RECEIVED', tone: 'good', route: 'accounting' },
  { id: 'DOC-15', title: 'Audit Working Papers', trigger: 'Assigned procedures', owner: 'Preparer / Senior · reviewer', status: 'SUBMITTED', tone: 'warn', route: 'audit' },
  { id: 'DOC-16', title: 'Working Paper Conclusion Summary', trigger: 'Conclusions available', owner: 'System aggregate · Senior submits', status: 'FROZEN', tone: 'good', route: 'audit' },
  { id: 'DOC-17', title: 'Draft Financial Statements', trigger: 'Reviewed accounting inputs', owner: 'Named Senior · reviewer', status: 'DRAFT V06', tone: 'warn', route: 'accounting' },
  { id: 'DOC-18', title: 'Management Information Request Letter', trigger: 'Draft FS dispatch', owner: 'Senior / Manager · client responds', status: 'SENT', tone: 'warn', route: 'reviews' },
  { id: 'DOC-19', title: 'Client Response Record', trigger: 'Draft decision / information response', owner: 'Client authority · Senior evaluates', status: 'REVISED RESPONSE', tone: 'warn', route: 'client-communications' },
  { id: 'DOC-20', title: 'Manager / Partner Review Record', trigger: 'Review package submission', owner: 'Manager / Partner / specialists', status: 'IN REVIEW', tone: 'danger', route: 'reviews' },
  { id: 'DOC-21', title: 'Audit Opinion', trigger: 'Professional conclusion', owner: 'Partner / signatory', status: 'SELECTED · PENDING RELEASE', tone: 'warn', route: 'reviews' },
  { id: 'DOC-22', title: 'Final Audit Report', trigger: 'Final discussion + release gates', owner: 'Authorized signatory', status: 'PENDING PROTECTION', tone: 'danger', route: 'release' },
  { id: 'DOC-23', title: 'Final Financial Statements', trigger: 'Matched final package', owner: 'Management · technical approvals', status: 'PENDING RELEASE', tone: 'danger', route: 'release' },
  { id: 'DOC-24', title: 'Invoice', trigger: 'Final report / FS issued', owner: 'Finance', status: 'DRAFT', tone: 'neutral', route: 'blueprint' },
  { id: 'DOC-25', title: 'Staff Time Record', trigger: 'Work throughout lifecycle', owner: 'Named staff · time approver', status: 'IN PROGRESS', tone: 'warn', route: 'blueprint' },
  { id: 'DOC-26', title: 'Engagement Cost Summary', trigger: 'Time / expense closeout', owner: 'Finance · management approval', status: 'PENDING CUTOFF', tone: 'neutral', route: 'blueprint' },
]

export const v5RoleMatrix = [
  { role: 'Client contributor', surface: 'Assigned requests, uploads, readiness and published deliverables', boundary: 'No private reviews, cost rates, audit file or opinion authority', icon: 'users', tone: 'blue' },
  { role: 'Client management approver', surface: 'Exact EL and Draft FS decisions, management-responsibility inputs', boundary: 'Cannot select an auditor opinion or clear an audit review', icon: 'check-circle', tone: 'green' },
  { role: 'Junior / preparer', surface: 'Assigned procedures, working papers and canonical time', boundary: 'Cannot self-clear significant independent review', icon: 'clipboard', tone: 'navy' },
  { role: 'Audit Senior', surface: 'Readiness, preparation, FS and conclusion-summary submission', boundary: 'Cannot approve the partner opinion or unrestricted finance data', icon: 'workflow', tone: 'blue' },
  { role: 'Audit Manager', surface: 'Review package, deadlines, findings and client-response evaluation', boundary: 'Cannot automatically sign or bypass a release blocker', icon: 'shield', tone: 'amber' },
  { role: 'Audit Partner / signatory', surface: 'Acceptance, continuance, opinion, discussion and authorized release', boundary: 'Cannot rewrite records policy or ignore a confirmed prohibition', icon: 'key', tone: 'purple' },
  { role: 'Finance team', surface: 'Rates, fee approvals, payment allocation, invoice and cost close', boundary: 'Cannot change technical conclusions or audit opinion', icon: 'calculator', tone: 'green' },
  { role: 'EQR / records / security', surface: 'Independent review, protection, recovery and scoped operations', boundary: 'Operational access does not create professional authority', icon: 'archive', tone: 'purple' },
]

export const v5NotificationMatrix = [
  { trigger: 'Assessment missing information', recipients: 'Assigned staff / client contact', action: 'Request missing items; close only on evaluated response' },
  { trigger: 'Fee submitted / changes requested', recipients: 'Current approver + preparer', action: 'Act on the exact estimate revision; stop stale approval reminders' },
  { trigger: 'EL sent / rejected / signed', recipients: 'Client + engagement owner', action: 'Track delivery separately from acceptance' },
  { trigger: 'Advance verified or reversed', recipients: 'Finance + activation owner', action: 'Re-evaluate eligibility; do not notify with bank-sensitive payloads' },
  { trigger: 'Portal onboarding authorized', recipients: 'Named verified client', action: 'Secure credential/instruction delivery; never ordinary stored password email' },
  { trigger: 'Announcement issued', recipients: 'Verified client contacts', action: 'Prepare requested items; link the current request manifest' },
  { trigger: 'Document uploaded or marked ready', recipients: 'Audit Senior + Audit Manager', action: 'Create Senior task and Manager alert; dedupe unchanged events' },
  { trigger: 'Submission rejected / clarification needed', recipients: 'Assigned client owner', action: 'Correct scope, period or completeness or supply an explanation' },
  { trigger: 'Workpaper/summary submitted', recipients: 'Next-level reviewer', action: 'Review exact submission and summary' },
  { trigger: 'Review point responded', recipients: 'Authorized clearing reviewer', action: 'Prevent responder self-clearance' },
  { trigger: 'Draft FS + information letter sent', recipients: 'Management / client contact', action: 'Review the exact pair by deadline' },
  { trigger: 'Draft rejected', recipients: 'Senior + Manager', action: 'Obtain explanation and assess revision' },
  { trigger: 'Information overdue', recipients: 'Client + Senior + Manager → Partner', action: 'Continue until evaluated disposition' },
  { trigger: 'Material input changed', recipients: 'Affected reviewer + Partner', action: 'Re-evaluate approvals immediately' },
  { trigger: 'Final discussion due', recipients: 'Engagement owner', action: 'Record actual discussion, not invitation' },
  { trigger: 'Final report/FS issued', recipients: 'Permitted client + Finance', action: 'Deliver exact package and create one draft billing milestone' },
  { trigger: 'Time/cost close pending', recipients: 'Staff + approvers + Finance', action: 'Resolve missing entries/rates and finalize a versioned summary' },
  { trigger: 'Access/records/recovery failure', recipients: 'Security / records / operations owner', action: 'Contain, reconcile and retain evidence' },
]

export const v5JourneySteps = [
  { number: '01', gate: 'G0', phase: 'Acquire & accept', title: 'Configure the firm baseline', action: 'Admin pins the approved roles, templates, methodology, service profile, repositories and recovery assumptions.', outcome: 'Synthetic outcome: G0 is ready only when the configured controls and owners are visible.', control: 'Version pin, service capability profile, named owner', route: 'architecture', routeLabel: 'Open architecture map', icon: 'settings', tone: 'blue' },
  { number: '02', gate: 'G1', phase: 'Acquire & accept', title: 'Search for the legal entity', action: 'The team searches the practice register before creating a duplicate client or assuming a matching email domain is the same entity.', outcome: 'Synthetic outcome: Northstar Trading receives a stable client ID and scoped relationship record.', control: 'Client ID, registration, source/date for facts', route: 'clients', routeLabel: 'Open clients & acceptance', icon: 'search', tone: 'blue' },
  { number: '03', gate: 'G1', phase: 'Acquire & accept', title: 'Choose new or existing route', action: 'The owner selects a new-client acceptance or current-period continuation route for the requested service and period.', outcome: 'Synthetic outcome: a returning client still requires fresh current-period facts and a separate decision.', control: 'Service, period, prior engagement link', route: 'clients', routeLabel: 'Open clients & acceptance', icon: 'briefcase', tone: 'navy' },
  { number: '04', gate: 'G1', phase: 'Acquire & accept', title: 'Open the 62-question acceptance', action: 'Compliance assigns the versioned questionnaire, evidence references and response owners.', outcome: 'Synthetic outcome: Unknown or missing mandatory information remains a hold.', control: 'Question/rule version, applicability, evidence', route: 'clients', routeLabel: 'Open clients & acceptance', icon: 'list-check', tone: 'blue' },
  { number: '05', gate: 'G1', phase: 'Acquire & accept', title: 'Resolve holds and specialist reviews', action: 'The team resolves identity, independence, integrity, AML/CFT and specialist evidence before routing the result.', outcome: 'Synthetic outcome: one cleared item does not hide another concurrent blocker.', control: 'Clearance, explanation, non-overridable prohibition', route: 'clients', routeLabel: 'Open clients & acceptance', icon: 'shield', tone: 'amber' },
  { number: '06', gate: 'G1', phase: 'Acquire & accept', title: 'Record the partner decision', action: 'The authorized partner accepts, rejects, continues, or places the exact assessment revision on hold.', outcome: 'Synthetic outcome: recommendation and human decision are stored as separate records.', control: 'Authority, revision, rationale, idempotency', route: 'clients', routeLabel: 'Open clients & acceptance', icon: 'check-circle', tone: 'green' },
  { number: '07', gate: 'G2', phase: 'Commercial onboarding', title: 'Prepare the staff-level cost estimate', action: 'Finance and the preparer enter Junior-to-Partner hours, effective cost rates, selling rates, direct expenses and assumptions.', outcome: 'Synthetic outcome: 140 hours produce QAR 25,000 labour cost plus QAR 1,000 travel.', control: 'Exact Decimal arithmetic, protected rate versions', route: 'blueprint', routeLabel: 'Open v5 operating model', icon: 'calculator', tone: 'blue' },
  { number: '08', gate: 'G2', phase: 'Commercial onboarding', title: 'Route fee approvals and quotation', action: 'The estimate goes through the configured Manager, Finance and Partner approval matrix before quotation issue.', outcome: 'Synthetic outcome: the approved fixed fee is QAR 36,000; internal cost rates stay private.', control: 'Approval level, discount/fee revision, quotation linkage', route: 'blueprint', routeLabel: 'Open v5 operating model', icon: 'check-circle', tone: 'green' },
  { number: '09', gate: 'G3', phase: 'Commercial onboarding', title: 'Generate, send and sign the EL', action: 'The approved quotation populates the actual EL template, which is reviewed, emailed before portal access, and signed electronically or on paper.', outcome: 'Synthetic outcome: EL-2026-01 is signed by the named client representative; delivery and acceptance remain distinct.', control: 'Template version, recipient, signature method, source hash', route: 'blueprint', routeLabel: 'Open v5 operating model', icon: 'file', tone: 'navy' },
  { number: '10', gate: 'G4', phase: 'Commercial onboarding', title: 'Verify advance and activate the portal', action: 'Finance confirms the QAR 9,000 advance is received and allocated to this engagement before access is provisioned.', outcome: 'Synthetic outcome: one named client identity receives one scoped setup path; partial or reversed payment stays blocked.', control: 'Payment Entry reference, allocation, setup-only session', route: 'blueprint', routeLabel: 'Open v5 operating model', icon: 'key', tone: 'amber' },
  { number: '11', gate: 'G5', phase: 'Plan & prepare', title: 'Approve plan, team and deadlines', action: 'The Senior and Manager version headcount, role hours, duration, fieldwork dates, mode and responsibilities.', outcome: 'Synthetic outcome: the plan is linked to the approved estimate instead of inventing capacity.', control: 'Named team, hours, mode, deadline, plan revision', route: 'engagements', routeLabel: 'Open engagement workspace', icon: 'calendar', tone: 'blue' },
  { number: '12', gate: 'G5', phase: 'Plan & prepare', title: 'Issue the Audit Announcement Letter', action: 'The approved plan generates the named announcement with timing, team contact, preparation instructions and linked PBC IDs.', outcome: 'Synthetic outcome: the announcement is a versioned artifact; it is not replaced by a generic portal notification.', control: 'Plan revision, request manifest, delivery record', route: 'engagements', routeLabel: 'Open engagement workspace', icon: 'send', tone: 'navy' },
  { number: '13', gate: 'G5', phase: 'Plan & prepare', title: 'Collect electronic and physical readiness', action: 'The client uploads an electronic file or marks a hard-copy item ready using the explicit delivery-method field.', outcome: 'Synthetic outcome: readiness, receipt, suitability and physical custody remain separate states.', control: 'Electronic / hard copy / mixed method, custody', route: 'pbc', routeLabel: 'Open PBC portal', icon: 'inbox', tone: 'amber' },
  { number: '14', gate: 'G5', phase: 'Plan & prepare', title: 'Declare fieldwork ready', action: 'The Senior evaluates critical items, team assignment and holds; the Manager is alerted with the Senior on relevant submissions.', outcome: 'Synthetic outcome: missing critical evidence prevents an unqualified ready-to-start label.', control: 'Readiness checklist, Senior task, Manager alert', route: 'audit', routeLabel: 'Open Audit & fieldwork', icon: 'clipboard', tone: 'warn' },
  { number: '15', gate: 'G5', phase: 'Execute', title: 'Receive the TB and prior-year FS', action: 'The accountant preserves the current Excel/CSV receipt and explicitly requests the prior audited FS where the entity is ongoing.', outcome: 'Synthetic outcome: source provenance, leading-zero account codes and prior-period applicability are visible.', control: 'Source hash, parser profile, prior-year package', route: 'accounting', routeLabel: 'Open Accounting & TB', icon: 'upload', tone: 'amber' },
  { number: '16', gate: 'G5', phase: 'Execute', title: 'Validate and promote the source', action: 'The accountant previews columns, checks locale/signs, control totals, duplicate keys and row limits before promoting a new generation.', outcome: 'Synthetic outcome: the 14-account fixture balances at QAR 1,820,000 per side with zero signed sum.', control: 'Staged dataset, validation report, generation', route: 'accounting', routeLabel: 'Open Accounting & TB', icon: 'database', tone: 'blue' },
  { number: '17', gate: 'G5', phase: 'Execute', title: 'Map and reconcile every balance', action: 'The package maps non-zero accounts to the approved taxonomy and records differences in named reconciliation workspaces.', outcome: 'Synthetic outcome: the QAR 12,500 receivables difference remains visible for evaluation.', control: 'Mapping version, lead schedule, reconciliation owner', route: 'accounting', routeLabel: 'Open Accounting & TB', icon: 'workflow', tone: 'navy' },
  { number: '18', gate: 'G5', phase: 'Execute', title: 'Apply only an eligible adjustment', action: 'The team documents AJ-001, distinguishes reflected from proposed journals, and creates a source-bound Adjustment Plan.', outcome: 'Synthetic outcome: a replacement TB that already includes AJ-001 does not double-apply QAR 5,000.', control: 'Logical journal revision, source reflection, idempotency', route: 'accounting', routeLabel: 'Open Accounting & TB', icon: 'calculator', tone: 'amber' },
  { number: '19', gate: 'G5', phase: 'Execute', title: 'Prepare the reviewed Draft FS', action: 'The named Senior prepares the IFRS-profile package from the selected source, mappings, adjustments, comparative bridge, disclosures and cash-flow workings.', outcome: 'Synthetic outcome: missing notes or cash-flow inputs remain named completion tasks instead of invented values.', control: 'FS package revision, calculation/render version', route: 'accounting', routeLabel: 'Open Accounting & TB', icon: 'file', tone: 'navy' },
  { number: '20', gate: 'G5', phase: 'Execute', title: 'Tailor programmes and materiality', action: 'The audit team pins methodology versions, records materiality rationale, links risks/assertions to procedures and identifies populations.', outcome: 'Synthetic outcome: software highlights coverage; professionals choose thresholds and responses.', control: 'Programme version, risk/assertion link, rationale', route: 'audit', routeLabel: 'Open Audit & fieldwork', icon: 'chart', tone: 'blue' },
  { number: '21', gate: 'G6', phase: 'Execute', title: 'Freeze workpapers and the conclusion summary', action: 'The Senior submits exact workpaper revisions and the automatically generated summary manifest, including incomplete or excluded work.', outcome: 'Synthetic outcome: the reviewer receives one reconstructable package rather than a live “latest” file.', control: 'Snapshot IDs, summary revision, selected submissions', route: 'audit', routeLabel: 'Open Audit & fieldwork', icon: 'archive', tone: 'green' },
  { number: '22', gate: 'G6', phase: 'Execute', title: 'Review findings and the hard-copy pack', action: 'Manager/Partner review points, misstatements, management actions and any controlled print/index pack without deleting history.', outcome: 'Synthetic outcome: AR-019 stays a significant open point until its response and evidence are cleared.', control: 'Review point, severity, response, print custody', route: 'reviews', routeLabel: 'Open Reviews & approvals', icon: 'message', tone: 'danger' },
  { number: '23', gate: 'G7', phase: 'Conclude', title: 'Dispatch Draft FS with the Information Request Letter', action: 'The reviewed Draft FS and named Management Information Request Letter are sent as one exact versioned pair with deadlines.', outcome: 'Synthetic outcome: a pair is not marked delivered when only one component is present.', control: 'Dispatch ID, paired hashes, recipients, deadlines', route: 'reviews', routeLabel: 'Open Reviews & approvals', icon: 'send', tone: 'navy' },
  { number: '24', gate: 'G7', phase: 'Conclude', title: 'Capture client rejection or acceptance', action: 'Management accepts or rejects the exact draft; a rejection includes an explanation and remains separate from information-item responses.', outcome: 'Synthetic outcome: client silence, download or an old-version response cannot approve the current package.', control: 'Exact draft revision, actor authority, response evidence', route: 'client-communications', routeLabel: 'Open client communications', icon: 'message', tone: 'amber' },
  { number: '25', gate: 'G7', phase: 'Conclude', title: 'Review valid changes and resend', action: 'The Senior evaluates a requested correction, updates the controlled accounting/FS revision, and creates a new paired dispatch where required.', outcome: 'Synthetic outcome: the prior draft response remains historical and the revised package has a new version.', control: 'Change-impact case, new draft/letter versions', route: 'reviews', routeLabel: 'Open Reviews & approvals', icon: 'refresh', tone: 'blue' },
  { number: '26', gate: 'G7', phase: 'Conclude', title: 'Follow up information items independently', action: 'The team reminds owners, records calls or meetings, evaluates nonresponse and escalates material items even after FS acceptance.', outcome: 'Synthetic outcome: outstanding information does not silently become answered or satisfactory.', control: 'Item-level disposition, reminder dedupe, escalation', route: 'client-communications', routeLabel: 'Open client communications', icon: 'bell', tone: 'warn' },
  { number: '27', gate: 'G7', phase: 'Conclude', title: 'Complete Manager, Partner and EQR review', action: 'The final package binds workpapers, summary, FS, responses, findings, representations and the applicable independent quality review.', outcome: 'Synthetic outcome: an unresolved EQR or significant review point blocks completion.', control: 'Review package, authority, EQR applicability', route: 'reviews', routeLabel: 'Open Reviews & approvals', icon: 'shield', tone: 'purple' },
  { number: '28', gate: 'G8', phase: 'Conclude', title: 'Select an approved opinion format', action: 'The Partner chooses an approved opinion family and records rationale, evidence and unresolved implications.', outcome: 'Synthetic outcome: opinion selection is not calculated from score, payment or client satisfaction.', control: 'Template catalogue, signatory authority, rationale', route: 'reviews', routeLabel: 'Open Reviews & approvals', icon: 'check-circle', tone: 'purple' },
  { number: '29', gate: 'G8', phase: 'Conclude', title: 'Record the actual final client discussion', action: 'The Partner records date, method, attendees, exact versions, matters discussed, comments, actions and disagreements.', outcome: 'Synthetic outcome: a calendar invitation alone cannot satisfy the discussion gate.', control: 'Discussion record, attendee capacity, package versions', route: 'client-communications', routeLabel: 'Open client communications', icon: 'users', tone: 'blue' },
  { number: '30', gate: 'G8', phase: 'Conclude', title: 'Freeze, sign and protect the final candidate', action: 'The signatory verifies matching report/FS, signatures, manifest, records protection and the current generation before creating one release event.', outcome: 'Synthetic outcome: a relevant source change while impact processing is stopped blocks stale release.', control: 'Manifest digest, signature lineage, protection observation', route: 'release', routeLabel: 'Open Release & archive', icon: 'lock', tone: 'danger' },
  { number: '31', gate: 'G8', phase: 'Conclude', title: 'Checkpoint and deliver electronic plus physical outputs', action: 'The records owner creates the protected checkpoint, then tracks exact electronic delivery and print/custody records separately.', outcome: 'Synthetic outcome: retrying delivery reuses the same release identity and does not re-render or re-issue.', control: 'Release event, checkpoint, recipient and custody log', route: 'release', routeLabel: 'Open Release & archive', icon: 'archive', tone: 'purple' },
  { number: '32', gate: 'G9', phase: 'Commercial close', title: 'Create the final invoice once', action: 'Finance drafts the QAR 36,000 fixed-fee invoice from the issued milestone and allocates the confirmed QAR 9,000 advance once.', outcome: 'Synthetic outcome: the remaining balance is QAR 27,000; release or delivery retries do not duplicate billing.', control: 'ERPNext invoice link, advance allocation, idempotency', route: 'blueprint', routeLabel: 'Open v5 operating model', icon: 'calculator', tone: 'green' },
  { number: '33', gate: 'G9', phase: 'Commercial close', title: 'Finalize time, cost and variance', action: 'Finance approves canonical timesheets and expenses, preserves rate history, and compares the original estimate with actuals.', outcome: 'Synthetic outcome: 156 hours and QAR 28,700 actual service cost produce QAR 7,300 contribution (20.28%).', control: 'Timesheet approval, cutoff, cost snapshot, variance', route: 'blueprint', routeLabel: 'Open v5 operating model', icon: 'chart', tone: 'blue' },
  { number: '34', gate: 'G10', phase: 'Archive & recovery', title: 'Assemble the complete archive', action: 'Records assembles the 26 outputs, structured history, physical custody, release evidence and observed protection state.', outcome: 'Synthetic outcome: archive state is separate from invoice paid and from the next-period decision.', control: 'Archive manifest, record profile, custody and hashes', route: 'release', routeLabel: 'Open Release & archive', icon: 'folder', tone: 'purple' },
  { number: '35', gate: 'G10', phase: 'Archive & recovery', title: 'Rehearse restore quarantine', action: 'Operations restores an older database, fences outward effects, reconciles the external checkpoint and reconstructs the historical release identity.', outcome: 'Synthetic outcome: the old node cannot issue a duplicate report or invoice while recovery is unresolved.', control: 'Recovery epoch, quarantine, checkpoint reconciliation', route: 'integration', routeLabel: 'Open Integration health', icon: 'refresh', tone: 'amber' },
  { number: '36', gate: 'G10', phase: 'Archive & recovery', title: 'Open next-period continuation', action: 'The partner creates a fresh continuation shell, carries forward references only, and records RENEW, NON_RENEW or WITHDRAW.', outcome: 'Synthetic outcome: prior samples, conclusions and approvals remain historical; the new period starts with fresh facts.', control: '30-question template, new period, closeout disposition', route: 'engagements', routeLabel: 'Open engagement workspace', icon: 'refresh', tone: 'blue' },
]
